/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData user_alt_solid = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData microphone_solid = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData list_ul_solid = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData play = const IconData(0xe81b, fontFamily: _kFontFam);
}
